name: Call Reusable Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-sbom-upload:
    if: github.event_name == 'push'
    uses: appsecdemos/reusable-workflows/.github/workflows/sbom_upload.yml@v1

  call-dependency-review:
    if: github.event_name == 'pull_request'
    uses: appsecdemos/reusable-workflows/.github/workflows/dependency_review.yml@v1